From: Praline <ibivu@cs.vu.nl>
To: abbasriz@buffalo.edu
Subject: PRALINE results for 'grouped_praline_psiblast_job' are ready

JOB_ID: grouped_praline_psiblast_job
PRALINE computation time was 3984.0 seconds

You can now access your results at the below URL for a maximum of 15 days from now
http://zeus.few.vu.nl/jobs/c905f8399ee933337849bffa993cad3f/

*Some statistics for your alignment
*----------------------------------
*Alignment score = 1666800.00
*Alignment score per aligned residue pair = 16.50
*Sequence identities = 78644
*Percent sequence identity = 0.78
*Number of sequences = 22
*Alignment length = 528
*Number of residues = 10109
*Number of gaps = 1507
*----------------------------------

THE IBIVU TEAM
